import type { GeneratedPRD } from "./prdGenerator";

export function formatPRDComment(prd: GeneratedPRD): string {
  const sections: string[] = [];

  sections.push(`
🤖 AI-GENERATED PRD — ${prd.title}
Version: ${prd.version} | Status: ${prd.status} | Confidence: ${(prd.prdConfidence * 100).toFixed(0)}%
Priority: ${prd.priority} | Effort: ${prd.effortEstimate}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  `.trim());

  sections.push(`
📌 PROBLEM STATEMENT
${prd.problemStatement}

💡 PROPOSED SOLUTION
${prd.proposedSolution}

✅ DEFINITION OF DONE
${prd.successDefinition}
  `.trim());

  if (prd.userPersonas.length > 0) {
    sections.push(`
👥 USER PERSONAS
${prd.userPersonas.map((p) => `• ${p.persona}: ${p.need}`).join("\n")}
    `.trim());
  }

  sections.push(`
📋 USER STORIES & ACCEPTANCE CRITERIA
${prd.userStories
  .map(
    (story) => `
[${story.id}] [${story.priority.toUpperCase()}]
${story.story}

Acceptance Criteria:
${story.acceptanceCriteria.map((ac) => `  ✓ ${ac}`).join("\n")}
`
  )
  .join("\n")}
  `.trim());

  if (prd.technicalRequirements.endpoints.length > 0) {
    sections.push(`
🔌 API ENDPOINTS
${prd.technicalRequirements.endpoints
  .map(
    (e) => `
${e.method} ${e.path}
Description: ${e.description}
Auth Required: ${e.authRequired ? "Yes" : "No"}
Request: ${e.requestBody || "None"}
Response: ${e.responseShape}
${e.notes ? `Notes: ${e.notes}` : ""}
`
  )
  .join("\n---\n")}
    `.trim());
  }

  if (prd.technicalRequirements.dataModel.length > 0) {
    sections.push(`
🗄️ DATA MODEL CHANGES
${prd.technicalRequirements.dataModel
  .map(
    (d) =>
      `Table: ${d.table} (${d.changes})\n${d.fields.map((f) => `  + ${f}`).join("\n")}`
  )
  .join("\n\n")}
    `.trim());
  }

  if (prd.nonFunctionalRequirements.length > 0) {
    sections.push(`
⚡ NON-FUNCTIONAL REQUIREMENTS
${prd.nonFunctionalRequirements
  .map(
    (r) =>
      `• [${r.type.toUpperCase()}] ${r.requirement}\n  Verify: ${r.measurable}`
  )
  .join("\n")}
    `.trim());
  }

  if (prd.outOfScope.length > 0) {
    sections.push(`
🚫 OUT OF SCOPE
${prd.outOfScope.map((o) => `• ${o}`).join("\n")}
    `.trim());
  }

  if (prd.openQuestions.length > 0) {
    sections.push(`
❓ OPEN QUESTIONS
${prd.openQuestions
  .map(
    (q) => `
Q: ${q.question}
Impact: ${q.impact}
Default Assumption: ${q.defaultAssumption}
Owner: ${q.owner}
`
  )
  .join("\n")}
    `.trim());
  }

  if (prd.risks.length > 0) {
    sections.push(`
⚠️ RISKS
${prd.risks
  .map(
    (r) =>
      `• [${r.probability.toUpperCase()}] ${r.risk}\n  Mitigation: ${r.mitigation}`
  )
  .join("\n")}
    `.trim());
  }

  sections.push(`
📊 COMPLEXITY SUMMARY
Score: ${prd.complexitySummary.score}/10
Optimistic: ${prd.complexitySummary.effortOptimistic}
Realistic: ${prd.complexitySummary.effortRealistic}
Pessimistic: ${prd.complexitySummary.effortPessimistic}

Key Drivers:
${prd.complexitySummary.keyComplexityDrivers.map((d) => `• ${d}`).join("\n")}
  `.trim());

  sections.push(`
📈 SUCCESS METRICS
${prd.successMetrics
  .map(
    (m) =>
      `• ${m.metric}: target ${m.target} (baseline: ${m.baseline})\n  Measure via: ${m.measurementMethod}`
  )
  .join("\n")}
  `.trim());

  sections.push(`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRD Confidence: ${(prd.prdConfidence * 100).toFixed(0)}%
${prd.confidenceNotes}

This PRD was generated by AI and requires human review before development begins.
  `.trim());

  return sections.join("\n\n");
}

export function estimateStoryPoints(complexityScore: number): number {
  if (complexityScore <= 2) return 1;
  if (complexityScore <= 4) return 3;
  if (complexityScore <= 6) return 5;
  if (complexityScore <= 8) return 8;
  return 13;
}
