import type { ImplementationOutput } from "../../types/agents";

export function formatEngineeringForJira(
  jiraKey: string,
  implementation: ImplementationOutput
): string {
  const lines: string[] = [
    `## Agentos — Engineering Output (${jiraKey})`,
    "",
    "### Summary",
    implementation.summary,
    "",
    "### Technical approach",
    implementation.technicalApproach,
    "",
    `*Estimate:* ${implementation.totalEstimateDays} days | *Confidence:* ${Math.round(implementation.confidenceScore * 100)}%`,
  ];

  if (implementation.components.length > 0) {
    lines.push("", "### Components");
    for (const c of implementation.components.slice(0, 10)) {
      lines.push(`- **${c.name}** (~${c.estimatedDays}d): ${c.description}`);
    }
    if (implementation.components.length > 10) {
      lines.push(`_…and ${implementation.components.length - 10} more components._`);
    }
  }

  if (implementation.apiChanges.length > 0) {
    lines.push("", "### API changes");
    for (const change of implementation.apiChanges.slice(0, 10)) {
      lines.push(`- ${change}`);
    }
  }

  if (implementation.databaseChanges.length > 0) {
    lines.push("", "### Database changes");
    for (const change of implementation.databaseChanges.slice(0, 10)) {
      lines.push(`- ${change}`);
    }
  }

  if (implementation.codingSummary) {
    lines.push("", "### Code summary", implementation.codingSummary);
  }

  if (implementation.codeChanges?.length) {
    lines.push("", "### Files changed");
    for (const change of implementation.codeChanges.slice(0, 20)) {
      lines.push(`- \`${change.filePath}\` (${change.action})`);
    }
    if (implementation.codeChanges.length > 20) {
      lines.push(`_…and ${implementation.codeChanges.length - 20} more files._`);
    }
  }

  if (implementation.blockers.length > 0) {
    lines.push("", "### Blockers");
    for (const blocker of implementation.blockers) {
      lines.push(`- ${blocker}`);
    }
  }

  lines.push("", "_Generated by Agentos engineering agent_");
  return lines.join("\n");
}
