import type { ValidationResult } from "../../types/pipeline";
import type { QaOutput } from "../../types/agents";

export function formatRcaComment(input: {
  jiraKey: string;
  validations: {
    prd?: ValidationResult;
    implementation?: ValidationResult;
    qa?: ValidationResult;
  };
  qa?: QaOutput;
  canaryCriticals?: Array<{ title: string; description: string }>;
  engineeringSummary?: string;
}): string {
  const lines: string[] = [
    `## Agentos RCA / Pipeline Details — ${input.jiraKey}`,
    "",
  ];

  if (input.engineeringSummary) {
    lines.push("### Engineering summary", input.engineeringSummary, "");
  }

  const validationSections = [
    ["PRD validation", input.validations.prd],
    ["Implementation validation", input.validations.implementation],
    ["QA validation", input.validations.qa],
  ] as const;

  for (const [label, result] of validationSections) {
    if (!result) continue;
    lines.push(`### ${label}`, `Passed: ${result.passed ? "yes" : "no"}`);
    if (result.issues?.length) {
      for (const issue of result.issues) {
        lines.push(`- ${issue.message}`);
      }
    }
    lines.push("");
  }

  const testCases = input.qa?.testCases ?? [];
  if (testCases.length) {
    lines.push("### Test cases");
    for (const tc of testCases.slice(0, 15)) {
      lines.push(`- **${tc.id}** ${tc.title} (${tc.type})`);
    }
    lines.push("");
  }

  if (input.canaryCriticals?.length) {
    lines.push("### Canary critical findings");
    for (const f of input.canaryCriticals) {
      lines.push(`- **${f.title}**: ${f.description.slice(0, 300)}`);
    }
    lines.push("");
  }

  lines.push("_Generated by Agentos pipeline_");
  return lines.join("\n");
}

export function formatPrdDescriptionSummary(input: {
  title: string;
  problemStatement: string;
  proposedSolution: string;
  successDefinition?: string;
}): string {
  return [
    "Agentos PRD Summary",
    "",
    `Title: ${input.title}`,
    "",
    "Problem:",
    input.problemStatement,
    "",
    "Solution:",
    input.proposedSolution,
    "",
    input.successDefinition ? `Success: ${input.successDefinition}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}
