import { getRepoContext } from "../../git-integration/gitCredentialsStore";
import { attachPRDToJira } from "../../prd/prdAttacher";
import { formatPRDComment } from "../../prd/prdFormatter";
import type { GeneratedPRD } from "../../prd/prdGenerator";
import { getPipelineCompletionSettings } from "../../pipeline/jira/intakeConfig";
import { getPipelineJiraClient } from "../../pipeline/jira/client";
import { attachQaReportToJira } from "../../qa/report/reportAttacher";
import type { QaExecutionReport } from "../../qa/report/reportGenerator";
import type { ImplementationOutput, PrdOutput, QaOutput } from "../../types/agents";
import { logger } from "../../utils/logger";
import { formatEngineeringForJira } from "./engineeringFormatter";

export interface GitPushInfo {
  targetBranch: string;
  commitSha: string;
  sourceBranch?: string;
}

function buildGitHubCommitUrl(workspace: string, repoSlug: string, sha: string): string {
  return `https://github.com/${workspace}/${repoSlug}/commit/${sha}`;
}

function buildGitHubBranchUrl(workspace: string, repoSlug: string, branch: string): string {
  return `https://github.com/${workspace}/${repoSlug}/tree/${encodeURIComponent(branch)}`;
}

export function formatGitPushComment(jiraKey: string, push: GitPushInfo): string {
  let workspace = "";
  let repoSlug = "";
  try {
    const ctx = getRepoContext();
    workspace = ctx.workspace;
    repoSlug = ctx.repoSlug;
  } catch {
    /* repo context may be unavailable */
  }

  const lines = [
    `## Agentos — code pushed (${jiraKey})`,
    "",
    `*Branch:* \`${push.targetBranch}\``,
    `*Commit:* \`${push.commitSha.slice(0, 12)}\``,
  ];

  if (workspace && repoSlug) {
    lines.push(
      `*View commit:* ${buildGitHubCommitUrl(workspace, repoSlug, push.commitSha)}`,
      `*View branch:* ${buildGitHubBranchUrl(workspace, repoSlug, push.targetBranch)}`
    );
  }

  if (push.sourceBranch) {
    lines.push(`*Based on:* \`${push.sourceBranch}\``);
  }

  lines.push("", "_Generated by Agentos engineering agent_");
  return lines.join("\n");
}

function formatPrdCommentFromOutput(prd: PrdOutput): string {
  const stub: GeneratedPRD = {
    title: prd.title,
    version: "1.0",
    status: "Draft",
    jiraKey: "",
    createdAt: new Date().toISOString(),
    priority: "Medium",
    effortEstimate: "TBD",
    problemStatement: prd.problemStatement,
    proposedSolution: prd.proposedSolution,
    successDefinition: prd.proposedSolution,
    userPersonas: [],
    userStories: prd.userStories.map((s, i) => ({
      id: `US-${i + 1}`,
      story: s,
      acceptanceCriteria: prd.acceptanceCriteria,
      priority: "must-have" as const,
    })),
    technicalRequirements: {
      endpoints: [],
      dataModel: [],
      systemsAffected: [],
      technicalAssumptions: [],
    },
    nonFunctionalRequirements: [],
    assumptions: [],
    outOfScope: [],
    openQuestions: prd.openQuestions.map((q) => ({
      question: q,
      impact: "",
      defaultAssumption: "",
      owner: "",
    })),
    risks: [],
    successMetrics: [],
    complexitySummary: {
      score: prd.confidenceScore * 10,
      effortOptimistic: "",
      effortRealistic: "",
      effortPessimistic: "",
      keyComplexityDrivers: [],
    },
    prdConfidence: prd.confidenceScore,
    confidenceNotes: "",
  };
  return formatPRDComment(stub);
}

/** Attach PRD to Jira after validation passes (idempotent via prd-generated label). */
export async function writePrdToTicket(
  jiraKey: string,
  prd: PrdOutput,
  generatedPrd?: GeneratedPRD
): Promise<boolean> {
  const settings = getPipelineCompletionSettings();
  if (!settings.attachPrdComment) return false;

  try {
    const client = getPipelineJiraClient();
    const labels = await client.getIssueLabels(jiraKey);
    if (labels.includes("prd-generated")) {
      return true;
    }

    if (generatedPrd) {
      await attachPRDToJira(jiraKey, generatedPrd);
    } else {
      await client.addPlainTextComment(jiraKey, formatPrdCommentFromOutput(prd));
      await client.addLabels(jiraKey, ["prd-generated", "agentos-discovery"]);
    }
    logger.info({ jiraKey }, "PRD written to Jira ticket");
    return true;
  } catch (err) {
    logger.warn({ err, jiraKey }, "failed to write PRD to Jira ticket");
    return false;
  }
}

/** Attach implementation plan and code summary to Jira (idempotent via agentos-engineering label). */
export async function writeEngineeringToTicket(
  jiraKey: string,
  implementation: ImplementationOutput
): Promise<boolean> {
  const settings = getPipelineCompletionSettings();
  if (!settings.attachEngineeringComment) return false;

  try {
    const client = getPipelineJiraClient();
    const labels = await client.getIssueLabels(jiraKey);
    if (labels.includes("agentos-engineering")) {
      return true;
    }

    const body = formatEngineeringForJira(jiraKey, implementation);
    await client.addPlainTextComment(jiraKey, body);
    await client.addLabels(jiraKey, ["agentos-engineering"]);
    logger.info({ jiraKey }, "engineering output written to Jira ticket");
    return true;
  } catch (err) {
    logger.warn({ err, jiraKey }, "failed to write engineering output to Jira ticket");
    return false;
  }
}

/** Post git push details as a Jira comment (always posted on successful push). */
export async function writeGitPushToTicket(
  jiraKey: string,
  push: GitPushInfo
): Promise<boolean> {
  try {
    const client = getPipelineJiraClient();
    await client.addPlainTextComment(jiraKey, formatGitPushComment(jiraKey, push));
    logger.info({ jiraKey, branch: push.targetBranch, sha: push.commitSha }, "git push written to Jira");
    return true;
  } catch (err) {
    logger.warn({ err, jiraKey }, "failed to write git push to Jira ticket");
    return false;
  }
}

/** Attach QA report to Jira after QA agent completes (idempotent via qa-generated label). */
export async function writeQaToTicket(
  jiraKey: string,
  qa: QaOutput,
  executionReport?: QaExecutionReport
): Promise<boolean> {
  const settings = getPipelineCompletionSettings();
  if (!settings.attachQaComment) return false;

  try {
    const client = getPipelineJiraClient();
    const labels = await client.getIssueLabels(jiraKey);
    if (labels.includes("qa-generated")) {
      return true;
    }

    await attachQaReportToJira(jiraKey, qa, executionReport);
    logger.info({ jiraKey }, "QA report written to Jira ticket");
    return true;
  } catch (err) {
    logger.warn({ err, jiraKey }, "failed to write QA report to Jira ticket");
    return false;
  }
}
